### PR TITLE
Improve API, prepare for VSCode, and other improvements

### PR DESCRIPTION
**Pull request by Glavin001**

### CODE REVIEW

**Comment by prettydiff** [comment]
The pull request looks good, except I would remove the .gitignore file.  Strange that it is there as git shouldn't transfer that file.

**Comment by Glavin001** [comment]
>  I would remove the .gitignore file. Strange that it is there as git shouldn't transfer that file.

What is the reason for removing `.gitignore` file?

**Comment by prettydiff** [comment]
It is a security best practice.  The items in the repository are things that already passed through the .gitignore file.  Should the code or application ever exist in a different location, such as a web server, a malicious user could look into the .gitignore file to see if the listed files are present in the alternate location for things like passwords or other sensitive information that shouldn't be available.

**Comment by Glavin001** [comment]
> It is a security best practice. The items in the repository are things that already passed through the .gitignore file

How will this work if you clone the repository?

Let's say I have the TypeScript `dist/` directory in the `.gitignore` for this project. If I remove the `.gitignore` then each person who clones will be required to either 1) know to manually create the appropriate `.gitignore` locally for themselves and add `dist/`, or 2) know to manually `git add` only files not in this somehow known excluding those on a secret *list of ignore files*, such as `dist/`. Both cases I think are bad.

I cannot speak to the security implications, only that the purpose of `.gitignore` is to provide information for every cloner's Git to hide those project specific files. I have never heard of not committing the `.gitignore` file.

**Comment by Glavin001** [comment]
@bitwiseman @szeck87 : Feel free to share your feedback. Thanks in advance.

**Comment by bitwiseman** [comment]
I have also neverver heard of not adding a `.gitignore` as a security concern. 

At best, I'd suggest that the philosophy of including or not including a `.gitignore` is a something to be handled in a separate PR.

**Comment by szeck87** [comment]
The code itself looks fine to me.  Just curious though, what is the benefit to using Bluebird versus native promises and async/await?

**Pull request merged**
