### PR TITLE
See #58. Improve Dependency not installed error message

### PR DESCRIPTION
**Pull request by Glavin001**
Improve error handling of https://github.com/Unibeautify/unibeautify/issues/58

### CODE REVIEW

**Comment by szeck87** [comment]
Should we put a link to the `@unibeautify/beautifier-name` package for installation instructions?  Or make that part of the debug feature?

**Comment by Glavin001** [comment]
It will be coming soon when I add more info to the dependency object. Similar to

https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee#L26-L27

**Comment by Glavin001** [comment]
I'm done making changes now 😄.

**Comment by Glavin001** [comment]
Published to v0.12.0

**Pull request merged**
