### PR TITLE
Close #21. Add helper methods

### LINKED ISSUE #21: Add functions/methods to retrieve options and beautifiers for a language
For the documentation, Atom Beautify, and potentially other things it would be best to centralize the logic that matches languages, beautifiers, and options all together.  The [docs scripts](https://github.com/Unibeautify/unibeautify.github.io/tree/develop/scripts/generate-docs) do a lot of this already, but should be in core Unibeautify so it can be reused.

- [x] List all loaded options (loadedOptions)
- [x] List all supported options (getOptionsSupportedForLanguage?)
- [x] List all loaded languages (getLoadedLanguages)
- [x] List all supported languages (supportedLanguages)
- [x] Get options supported by a beautifier for a language (getOptionsSupportedByBeautifierForLanguage)
- [x] Get languages for beautifier (getLanguagesForBeautifier)
- [x] Get languages supporting option (getLanguagesSupportingOption)
- [x] Get beautifiers for a language (getBeautifiersForLanguage)
- [x] Get beautifiers support for an option for a language (getBeautifiersSupportingOption)
- [x] Get language based on Atom Grammar and file extension (findLanguages)

### PR DESCRIPTION
**Pull request by Glavin001**
Close #21. Add helper methods

### CODE REVIEW

**Comment by szeck87** [comment]
For the most part this looks good.  For `[getBeautifiersSupportingOption](https://github.com/Unibeautify/unibeautify/blob/c33cbdc78c9bd930f9f78081f4a8a9dcc09eb6f1/src/beautifier.ts#L427-L440)` though, should we assume that the option being passed is supported for all languages that the returned list of beautifiers support?

**Comment by szeck87** [comment]
OK, I didn't realize "branches" on code coverage are different than typical repo branches.  To cover [line 511](https://github.com/Unibeautify/unibeautify/blob/feature/21/src/beautifier.ts#L511), need a beautifier without global options and just a single beautifier option that is boolean and equal to true.

```
  const beautifier2: Beautifier = {
    beautify: ({ Promise }) => {
      return Promise.resolve(beautifierResult);
    },
    name: "TestBeautify2",
    options: {
      [lang2.name]: true
    }
  };
...
  const result3 = Unibeautify.getOptionsForBeautifier(
    beautifier2,
    lang2,
    options
  );
  t.is(result2.globalOption, options.globalOption, "Include global option");
  t.is(
    result2.willBeReplaced,
    options.globalOption,
    "Replace global option with language-specific option"
  );
  t.deepEqual(result2, {
    globalOption: options.globalOption,
    willBeReplaced: options.globalOption
  });
```

**Comment by Glavin001** [comment]
> For getBeautifiersSupportingOption though, should we assume that the option being passed is supported for all languages that the returned list of beautifiers support?

@szeck87 : Good question

I think `getBeautifiersSupportingOption` should return whether or not the option is supported by any language for this beautifier -- this is how we use it in the docs generation currently -- and then additional filtering can be performed using:
 
```typescript
this.doesBeautifierSupportOptionForLanguage({
            beautifier,
            language,
            optionName
          })
```

These helpers are great starting points, however, if the developer wants something specific they will need to use methods more tailed specifically for this case, like `doesBeautifierSupportOptionForLanguage`.

**Comment by Glavin001** [comment]
Published to v0.6.0

**Pull request merged**
