### PR TITLE
Enable AppVeyor build

### PR DESCRIPTION
**Pull request by lassik**
It was disabled for some reason. Let's try to get it working :)

### CODE REVIEW

**Comment by stevenzeck** [comment]
@lassik what is the objective with this PR?

**Comment by lassik** [comment]
> @lassik what is the objective with this PR?

Getting AppVeyor to run unit tests for every PR (i.e. to behave as Travis now does). For Windows support.

**Comment by lassik** [comment]
Hmm, `build: off` is in the [official instructions for Node](https://www.appveyor.com/docs/lang/nodejs-iojs/). Does it just disable running the `build_script` instead of disabling AppVeyor completely?

**Comment by lassik** [comment]
All of the Renovate PRs seem to be green here: https://ci.appveyor.com/project/Glavin001/unibeautify/history

But the AppVeyor status badge in this repo's README says the status is unknown.

**Comment by stevenzeck** [comment]
Looks like it had the wrong badge.  I updated the README.md, it shows green now.

**Comment by lassik** [comment]
OK, cool 😄 And this PR was unnecessary since we're actually supposed to have `build: off`. I'll close it.

**Pull request closed without merging**
